active_locators:
  - mode: text
    value: Explore
    uses: 0
  - mode: text
    value: Log in
    uses: 0
actions:
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        uses: 4
inactive_locators:
  - mode: ''
    value: ''
    uses: 0
