active_locators:
  - mode: ''
    value: ''
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    uses: 0
actions:
  - verb: fill
    name: username
    locators:
      - mode: name
        value: session[username_or_email]
        uses: 0
  - verb: fill
    name: password
    locators:
      - mode: name
        value: session[password]
        uses: 0
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        uses: 0
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        uses: 0
