active_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
actions:
  - verb: click
    name: cancel
    locators:
      - mode: css
        value: '[aria-label="Close"]'
        index: 0
        uses: 4
