actions:
  - verb: click
    name: cancel
    locators:
      - mode: css
        value: '[aria-label="Close"]'
        index: 0
        uses: 5
      - mode: text
        value: Cancel
        index: 0
        uses: 0
      - mode: text
        value: Cancel
        index: 0
        uses: 0
      - mode: value
        value: Cancel
        index: 0
        uses: 0
      - mode: value
        value: Cancel
        index: 0
        uses: 0
locators:
  inclusions:
    -
  exclusions:
    -
