inactive_locators:
  - mode: text
    value: Cancel
    index: 0
    score: 0.0
  - mode: name
    value: session[password]
    index: 0
    score: 0.0
actions:
  - verb: click
    name: more
    locators:
      - mode: css
        value: '[aria-label="More"]'
        index: 0
        score: 0.1
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.5
active_locators:
  - mode: text
    value: Tweets & replies
    index: 0
    score: 0.0
