active_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
actions:
  - verb: click
    name: tweet
    locators:
      - mode: text
        value: Tweet
        index: 0
        uses: 3
