active_locators:
  - mode: ''
    value: ''
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    uses: 0
actions:
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        uses: 0
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        uses: 0
