locators:
  inclusions:
    - mode: text
      value: Explore
      index: 0
      uses: 4
    - mode: text
      value: Log in
      index: 0
      uses: 1
  exclusions:
    -
actions:
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        index: 0
        uses: 3
      - mode: text
        value: Log In
        index: 0
        uses: 0
      - mode: text
        value: Log in
        index: 0
        uses: 0
      - mode: value
        value: Log In
        index: 0
        uses: 0
      - mode: value
        value: Log in
        index: 0
        uses: 0
