active_locators:
  - mode: text
    value: Explore
    index: 0
    uses: 0
  - mode: text
    value: Log in
    index: 0
    uses: 0
actions:
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        index: 0
        uses: 2
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
