active_locators:
  - mode: text
    value: Explore
    index: 0
    score: 0.0
  - mode: text
    value: Log in
    index: 0
    score: 0.0
actions:
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        index: 0
        score: 0.1
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.5
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.0
