locators:
  inclusions:
    - mode: text
      value: Tweets & replies
      index: 0
      uses: 3
  exclusions:
    - mode: text
      value: Cancel
      index: 0
      uses: 1
    - mode: name
      value: session[password]
      index: 0
      uses: 0
actions:
  - verb: click
    name: more
    locators:
      - mode: css
        value: '[aria-label="More"]'
        index: 0
        uses: 3
      - mode: text
        value: More
        index: 0
        uses: 0
      - mode: text
        value: More
        index: 0
        uses: 0
      - mode: value
        value: More
        index: 0
        uses: 0
      - mode: value
        value: More
        index: 0
        uses: 0
