inactive_locators:
  - mode: text
    value: Cancel
    index: 0
    uses: 0
  - mode: name
    value: session[password]
    index: 0
    uses: 0
actions:
  - verb: click
    name: more
    locators:
      - mode: css
        value: '[aria-label="More"]'
        index: 0
        uses: 2
active_locators:
  - mode: text
    value: Tweets & replies
    index: 0
    uses: 0
