actions:
  - verb: fill
    name: username
    locators:
      - mode: name
        value: session[username_or_email]
        index: 0
        uses: 3
      - mode: name
        value: username
        index: 0
        uses: 0
      - mode: name
        value: username
        index: 0
        uses: 0
      - mode: id
        value: username
        index: 0
        uses: 0
      - mode: id
        value: username
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Username"]'
        index: 0
        uses: 0
      - mode: id
        value: Username
        index: 0
        uses: 0
  - verb: fill
    name: password
    locators:
      - mode: name
        value: session[password]
        index: 0
        uses: 3
      - mode: name
        value: password
        index: 0
        uses: 0
      - mode: name
        value: password
        index: 0
        uses: 0
      - mode: id
        value: password
        index: 0
        uses: 0
      - mode: id
        value: password
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Password"]'
        index: 0
        uses: 0
      - mode: id
        value: Password
        index: 0
        uses: 0
  - verb: click
    name: log_in
    locators:
      - mode: text
        value: Log in
        index: 0
        uses: 3
      - mode: text
        value: Log In
        index: 0
        uses: 0
      - mode: text
        value: Log in
        index: 0
        uses: 0
      - mode: value
        value: Log In
        index: 0
        uses: 0
      - mode: value
        value: Log in
        index: 0
        uses: 0
locators:
  inclusions:
    -
  exclusions:
    -
