active_locators:
  - mode: ''
    value: ''
    uses: 0
inactive_locators:
  - mode: text
    value: Cancel
    uses: 0
actions:
  - verb: click
    name: more
    locators:
      - mode: css
        value: '[aria-label="More"]'
        uses: 0
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        uses: 0
